add_newline = false
format = """
$git_state\
$git_branch\
$git_commit\
$git_status\
$hostname\
$directory\
$character
"""

[character]
success_symbol="[ɔ](green)"
error_symbol="[ɔ](bold)"

[env_var]
variable = "fish_platform_icon"
default = "?"
format = "[$env_value]($style) "

[git_branch]
format = "[$symbol$branch]($style) "

[git_commit]
tag_disabled = false
only_detached = false

[git_status]
format = '''([\[$all_status$ahead_behind\]]($style)
)'''

[directory]
truncate_to_repo = false
