add_newline = false
format = """
$git_state\
$git_branch\
$git_status\
$git_commit\
$hostname\
$directory\
$character
"""

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = "[$all_status$ahead_behind]($style)"

[git_commit]
tag_disabled = false
only_detached = false
format = """
[ \\($hash\\)]($style)
"""

[directory]
truncate_to_repo = false

[character]
success_symbol="[ɔ](green)"
error_symbol="[ɔ](red)"

